paths:
  # Accept file paths, directories, or glob patterns (strings or lists)
  genereviews_inputs:
    - ../data/genereviews                    # a directory (recurses 1 level)
    - ../data/genereviews/*.pdf               # glob pattern
  clinvar_inputs:
    - ../data/clinvar           # a directory
    - ../data/clinvar/*.json    # or explicit globs
  mitocarta_inputs:
    - ../data/mitocarta
    - ../data/mitocarta/*.json
  pdf_path: ../data/genereviews/Bookshelf_NBK1173.pdf      # can also be a .pdf
  variants_path: ../data/json_samples/clinvar_mito_sample.json
  genes_path: ../data/json_samples/mitocarta_pivot_sample.json
  index_dir: index

ingestion:
  use_unstructured: true                # if false or unstructured not installed, falls back to PyMuPDF or plain text
  chunk_tokens: 700
  chunk_overlap: 100

embedding:
  model_name: sentence-transformers/all-MiniLM-L6-v2
  batch_size: 64
  normalize: true

retrieval:
  top_k: 20
  enable_reranker: true
  rerank_top_k: 5
  reranker_model: BAAI/bge-reranker-base

generation:
  provider: llama_cpp
  model_path: ../models/qwen2.5-3b-instruct-q4_k_m.gguf   # or the 1.5B path
  temperature: 0.2
  max_tokens: 400
  num_ctx: 4096
  n_gpu_layers: 0       # CPU only
  n_threads: 8          # or your CPU core count
  n_batch: 256
  system_prompt: >
    You are a helpful FRENCH medical assistant. Answer using ONLY the provided context. If the
    answer is not in the context, say you don’t know. Include bracketed
    citations like [1], [2] that refer to the sources list provided.

pdf_metadata:
  source_url: "https://www.ncbi.nlm.nih.gov/books/"
  license_note: "© 1993-2025 University of Washington (GeneReviews) — noncommercial research use with attribution"

advanced:
  # Optionally override config path via environment variable CONFIG
  # Leave empty if not needed.
  allow_env_override: true
